@host=http://localhost:5195
POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName":"AAAA",
    "lastName":"DDD",
    "email": "abisakyn@gmail.com",
    "password": "A123456!"
}
